server:
  port: 8080

spring:
  application:
    name: shop

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}

discount:
  service:
    url: ${DISCOUNT_SERVICE_URL:http://localhost:8082}
