name: dr3-at

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - at-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.product
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - at-network
    depends_on:
      postgres:
        condition: service_healthy


  discount-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.discount
    container_name: discount-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - at-network


  shop-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.shop
    container_name: shop-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - DISCOUNT_SERVICE_URL=http://discount-service:8082

    networks:
      - at-network


networks:
  at-network:
    driver: bridge

volumes:
  postgres-data:

